# Generated by Django 3.2.25 on 2024-05-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_transaction_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='user',
            name='currency_preference',
        ),
    ]
